StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{60DE7068AFA5A77C}" {
   Id "SPC-Vehicle_M1126_M2_Name"
   Target_en_us "M1126 Infantry Carrier Vehicle - M2"
   Modified 1625191659
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
  }
  CustomStringTableItem "{60DE706B8166A069}" {
   Id "SPC-Vehicle_M1126_Name"
   Target_en_us "M1126 Infantry Carrier Vehicle"
   Modified 1625191662
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
  }
  CustomStringTableItem "{60DE706B8593A19E}" {
   Id "SPC-Vehicle_M1127_Name"
   Target_en_us "M1127 Reconnaissance Vehicle"
   Modified 1625191665
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
  }
  CustomStringTableItem "{60DE706B8BA06189}" {
   Id "SPC-Vehicle_M1128_Name"
   Target_en_us "M1128 Mobile Gun System"
   Modified 1625191667
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
  }
  CustomStringTableItem "{60DE706B8F0C5512}" {
   Id "SPC-Vehicle_M1129_Name"
   Target_en_us "M1129 Mortar Carrier"
   Modified 1625191671
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
  }
  CustomStringTableItem "{60DE706B8C7B1B9E}" {
   Id "SPC-Vehicle_M1130_Name"
   Target_en_us "M1130 Command Vehicle"
   Modified 1625191673
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
  }
  CustomStringTableItem "{60DE706B933A2034}" {
   Id "SPC-Vehicle_M1131_Name"
   Target_en_us "M1131 Fire Support Vehicle"
   Modified 1625191675
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
  }
  CustomStringTableItem "{60DE706B90B7F62F}" {
   Id "SPC-Vehicle_M1132_Name"
   Target_en_us "M1132 Engineer Squad Vehicle"
   Modified 1625191682
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
  }
  CustomStringTableItem "{60DE706B95F7B526}" {
   Id "SPC-Vehicle_M1133_Name"
   Target_en_us "M1133 Medical Evacuation Vehicle"
   Modified 1625191684
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
  }
  CustomStringTableItem "{60DE706B94BFD608}" {
   Id "SPC-Vehicle_M1134_Name"
   Target_en_us "M1134 Anti-Tank Guided Missile Vehicle"
   Modified 1625191687
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
  }
  CustomStringTableItem "{60DE706B995590E0}" {
   Id "SPC-Vehicle_M1135_Name"
   Target_en_us "M1135 Nuclear, Biological, Chemical Reconnaissance Vehicle"
   Modified 1625191689
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
  }
  CustomStringTableItem "{60DE706BBF401F9A}" {
   Id "SPC-Vehicle_M1196_Name"
   Target_en_us "M1196 Infantry Carrier Vehicle Dragoon"
   Modified 1625191692
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
  }
 }
}